### ISSUE TITLE
spelled preceding incorrectly

### ISSUE THREAD

**Issue by danvyle** [learn-co-curriculum/js-github-project#3]
spelled "preciding"

**Comment by maxwellbenton** [comment]
Hi @danvyle,

Thank you for opening this issue. Unfortunately, I am unable to find the spelling error you are referring to as I don't see `preceding` or `preciding` in this lesson's content. Is this issue meant for a different lesson?

**Comment by sgharms** [comment]
@danvyle Since it seems like we can't find the issue here and it's been two days without a response, I'm going to close this issue pending your update. If you can update this with answers to Max's question, we'll hop right on it. Thanks 💙
